from django.urls import path, include
import django.contrib.auth.urls
from . import views

app_name = 'shop'

urlpatterns = [
        path('', views.general.index, name='index'),
        path('log_in/', views.general.log_in, name='log_in'),
        path('log_out/', views.general.log_out, name='log_out'),
        path('sign_up/', views.general.sign_up, name='sign_up'),
        path('signup_success/', views.general.signup_success, name='signup_success'),
        path('login_success/', views.general.login_success, name='login_success'),
        path('product_search/', views.products.product_search, name='product_search'),
        path('balance/', views.customer.customer_balance, name='balance'),
        path('basket_add/', views.basket.basket_add, name='basket_add'),
        path('basket_detail/<str:basketname>/', views.basket.basket_detail, name='basket_detail'),
        path('basket_edit/<int:id>/', views.basket.basket_edit, name='basket_edit'),
        path('basket_delete/<int:id>/', views.basket.basket_delete, name='basket_delete'),
        path('basket_delete_success/', views.basket.basket_delete_success, name='basket_delete_success'),
        path('basket_payment/<int:id>/', views.basket.basket_payment, name='basket_payment'),
        path('basket_payment_success/', views.basket.basket_payment_success, name='basket_payment_success'),
        path('/<str:basketname>/', views.item.item_add, name='item_add'),
        path('item_edit/<int:id>', views.item.item_edit, name='item_edit'),
        path('item_delete/<int:id>', views.item.item_delete, name='item_delete'),
        path('/<str:basketname>/<int:id>/', views.item.item_detail, name='item_detail'),
        path('admin_console/', views.staff.admin_console, name='admin_console'),
        path('staff_customer_list/', views.staff.staff_customer_list, name='staff_customer_list'),
        path('staff_customer_detail/<int:id>', views.staff.staff_customer_detail, name='staff_customer_detail'),
        path('staff_customer_delete/<int:id>', views.staff.staff_customer_delete, name='staff_customer_delete'),
        path('staff_customer_delete_success/', views.staff.staff_customer_delete_success, name='staff_customer_delete_success'),
        path('staff_basket_list/<str:username>', views.staff.staff_basket_list, name='staff_basket_list'),
        path('staff_basket_detail/<int:id>', views.staff.staff_basket_detail, name='staff_basket_detail'),
        path('staff_basket_delete/<int:id>', views.staff.staff_basket_delete, name='staff_basket_delete'),
        path('staff_basket_delete_success/', views.staff.staff_basket_delete_success, name='staff_basket_delete_success'),
        path('staff_order_list/<str:username>/<str:basketname>', views.staff.staff_order_list, name='staff_order_list'),
        path('staff_order_detail/<int:id>', views.staff.staff_order_detail, name='staff_order_detail'),
        path('staff_order_delete/<int:id>', views.staff.staff_order_delete, name='staff_order_delete'),
        path('staff_order_delete_success/', views.staff.staff_order_delete_success, name='staff_order_delete_success'),
        path('staff_product_list/', views.staff.staff_product_list, name='staff_product_list'),
        path('staff_customer_list_total/', views.staff.staff_customer_list_total, name='staff_customer_list_total'),
        path('staff_basket_list_total/', views.staff.staff_basket_list_total, name='staff_basket_list_total'),
        path('staff_order_list_total/', views.staff.staff_order_list_total, name='staff_order_list_total'),
        path('staff_product_add/', views.staff.staff_product_add, name='staff_product_add'),
        path('staff_product_edit/', views.staff.staff_product_edit, name='staff_product_edit'),
        path('staff_product_detail/', views.staff.staff_product_detail, name='staff_product_detail'),
]