# Generated by Django 4.0.4 on 2022-04-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_basket_basket_detail_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
