# Generated by Django 4.0.4 on 2022-04-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_basket_created_date_basket_detail_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='status',
            field=models.TextField(default='unpaid'),
        ),
    ]
