# Generated by Django 4.0.4 on 2022-04-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_basket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket_detail',
            name='item_id',
            field=models.IntegerField(default=0),
        ),
    ]
