# Generated by Django 4.0.4 on 2022-04-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_basket_detail_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket_detail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
